### PR TITLE
(#9) support liquid inside markdownify content

### LINKED ISSUE #9: Liquid support in markdown files
Hi again, just noticed that Liquid blocks in markdown don't get parsed, is that something you would like to have? I could take a stab at making it work if you want to have it.

i.e. 
screenshot 2016-08-11 12 52 23

### PR DESCRIPTION
**Pull request by ntwcklng**
This closes #9

### CODE REVIEW

**Comment by juusaw** [comment]
Hi there!

This seems to break syntax highlighted code blocks. I get a `Liquid error: undefined method 'safe' for nil:NilClass` instead of the markup for every block. Can be reproduced by for example adding the following to a blog post

```
{% highlight ruby %}
puts 'test'
{% endhighlight %}
```

**Review by juusaw — CHANGES_REQUESTED** [review]
Currently breaks syntax highlighted code blocks. This must be addressed before merge.

**Comment by ntwcklng** [comment]
Unfortunately i didn't find a solution yet, do you have an idea?

**Comment by juusaw** [comment]
Fixed by #14

**Comment by juusaw** [comment]
Accidentally closed without merging. Will merge now, since #14 fixes the comment block problem.

**Review by juusaw — APPROVED** [review]

**Pull request merged**
