### PR TITLE
loop over each page in a thread to speed up generation

### PR DESCRIPTION
**Pull request by pauldambra**
PR referencing #25 

(untested here but only because I must have done something silly while trying to sort out the kids breakfast and check my work :))

### CODE REVIEW

**Review by juusaw — APPROVED** [review]
This works for me and notably reduces build time.

**Comment by juusaw** [comment]
One thing that I fear is what happens when spawning a new thread for each post on very large sites (thousands of posts). I think there's a chance that the system runs out of threads though that would require a very large number of posts (my OS seems to set the maximum to 61028 by default).

A more realistic concern might be that with a large number of short tasks the overhead of context switching between threads becomes a bottleneck for performance. I think it would be a good idea to implement a setting to disable multithread usage if a user encounters a problem related to this. I'll open an issue for that.

**Comment by pauldambra** [comment]
Hmm, yeah, that's a good point. Might be worth pushing​with into a queue
and having a configurable number of threads to pull and then process the
pages. Could be getting a bit fancy at that point though :)

**Comment by pauldambra** [comment]
@juusaw Added an implementation that limits the number of threads. I've pulled the number of threads from an environment variable to try and keep things simple.

**Comment by pauldambra** [comment]
Ha, I've just seen this is open. Feel free to merge it or close it :)

**Pull request closed without merging**
